
image: python:3.7.3

options:
  docker: true

pipelines:
  branches:
    staging:
      - step: 
          name: Files transfer
          script: # Dockercompose
            - scp -P 822 -r docker-compose.yml root@dui.dev:/nvram/neuraldistribution/staging/docker-compose.yml
            - scp -P 822 -r Dockerfile root@dui.dev:/nvram/neuraldistribution/staging/Dockerfile
            - scp -P 822 -r variables.env root@dui.dev:/nvram/neuraldistribution/staging/variables.env
            - scp -P 822 -r requirements.txt root@dui.dev:/nvram/neuraldistribution/staging/requirements.txt
            - scp -P 822 -r docker-entrypoint.sh root@dui.dev:/nvram/neuraldistribution/staging/docker-entrypoint.sh
      - step:
          name: Building docker

          script: # Name the image and create a docker image
            - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD dui.dev:5000
            - docker build -t dui.dev:5000/neuraldistribution:$BITBUCKET_BUILD_NUMBER .
            - docker push dui.dev:5000/neuraldistribution:$BITBUCKET_BUILD_NUMBER
      - step:
          name: Deploying dockers
          script:
            - ssh root@dui.dev -p 822 "cd $LOCALDIR/staging; " \
              " docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD dui.dev:5000; " \
              " docker stop neuraldistribution || true && docker rm neuraldistribution || true; " \
              " docker run -d -i -t -p 8000:5000 -v $LOCALDIR/staging/web:/web" \
              " --name neuraldistribution dui.dev:5000/neuraldistribution:$BITBUCKET_BUILD_NUMBER; "\
              " docker-compose up -d"

    master:
      - step:
          script:
            - ssh root@dui.dev -p 822 'cd /firecuda/staging; echo "test" > testMaster.txt '
