
image: python:3.7.3

options:
  docker: true

pipelines:
  branches:
    staging:
      - step:
          name: Building docker

          script: # Name the image and create a docker image
            - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD dui.dev:5000
            - docker build -t dui.dev:5000/neuraldistribution:$BITBUCKET_BUILD_NUMBER .
            - docker push dui.dev:5000/neuraldistribution:$BITBUCKET_BUILD_NUMBER
      - step:
          name: Deploying dockers
          script:
            - ssh root@dui.dev -p 822 "cd $LOCALDIR/staging; " \
              " docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD dui.dev:5000; " \
              " docker stop neuraldistribution || true && docker rm neuraldistribution || true; " \
              " docker run -d -i -t " \
              " --name=neuraldistribution dui.dev:5000/neuraldistribution:$BITBUCKET_BUILD_NUMBER; "

    master:
      - step:
          script:
            - ssh root@dui.dev -p 822 'cd /firecuda/staging; echo "test" > testMaster.txt '
