version: '2'
services:
  postgres:
    image: "postgres:11"
    container_name: "postgres_container"
    ports:
      - "8292:5432"
    volumes:
      - postgres_db-volume:/var/lib/postgresql/data

  influxdb:
    image: influxdb
    container_name: influxdb_container
    ports:
      - 8293:8086
    volumes:
      - influxdbdistribution-volume:/var/lib/influxdbdistribution
    environment:
      - INFLUXDB_ADMIN_PASSWORD=82xyPferj

  web:
    image: tiangolo/uwsgi-nginx-flask
    container_name: flask_container
    ports:
    - "5000:5000"
    volumes:
    - flask-volume:/var/lib/flask/code
volumes:
  postgres_db-volume:
    external: true
  
  influxdbdistribution-volume:
    external: true

  flask-volume:
    external: true