version: '3.5'

services:
  db:
    image: postgres

  internal_dashboard:
    build: .
    command: python /neural-distribution/internal_dashboard/app.py 
    volumes:
      - .:/neural-distribution/
    ports:
      - "8000:5000"

  customer:
    build: .
    command: python /neural-distribution/customers/app.py
    volumes:
      - .:/neural-distribution/
    ports:
      - "8001:5001"

  api:
    build: .
    command: python /neural-distribution/api/api.py
    volumes:
      - .:/neural-distribution/
    ports:
      - "8002:5002"