version: '3.5'

services:
  db:
    image: postgres

  internal_dashboard:
    build: .
    command: python /neuraldistribution/internal_dashboard/app.py 
    volumes:
      - .:/neuraldistribution/
    ports:
      - "8000:5000"
    env_file:
      - variables.env

  customer:
    build: .
    command: python /neuraldistribution/customers/app.py
    volumes:
      - .:/neuraldistribution/
    ports:
      - "8001:5001"
    env_file:
      - variables.env

  api:
    build: .
    command: python /neuraldistribution/api/api.py
    volumes:
      - .:/neuraldistribution/
    ports:
      - "8002:5002"
    env_file:
      - variables.env