version: '3'
services:
  neuraldistribution:
    image: neuraldistribution
    container_name: neuraldistribution
    restart: always
    ports:
    - 8000:5000
  
  postgres_distribution:
    image: postgres:11
    container_name: postgres_distribution
    restart: always
    environment:
    - POSTGRES_USER : postgres 
    - POSTGRES_PASSWORD : postgres 
    ports:
    - 8292:5432
    volumes:
    - /nvram/neuraldistribution/staging/postgresdistribution:/var/lib/postgresql/data

