version: '3'
services:
  flaskdistribution:
    build: .
    image: neuraldistribution:latest
    container_name: flask_distribution
    environment:
      DEVELOPMENT: STAGING
    ports:
    - 8000:5000
    volumes:
    - ./web:/web
    depends_on: 
    - postgres_distribution

  postgres_distribution:
    image: "postgres:11"
    container_name: postgres_distribution
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
    - 8292:5432
    volumes:
    - $LOCALDIR/postgresdistribution:/var/lib/postgresql/data

