version: '2'
services:
  web:
    build: .
    image: neuraldistribution:staging
    container_name: flask_distribution
    environment:
      DEVELOPMENT: STAGING
    ports:
    - "8000:5000"
    volumes:
    - ./web:/web
    depends_on: 
    - db

  db:
    image: "postgres:11"
    container_name: postgres_distribution
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - 8292:5432
    volumes:
    - postgresdistribution-volume:/var/lib/postgresdistribution/data


volumes:
  postgresdistribution-volume:
    external: true