version: '3'
services:

  postgres_distribution:
    image: "postgres:11"
    container_name: postgres_distribution
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
    - 8292:5432
    volumes:
    - $LOCALDIR/staging/postgresdistribution:/var/lib/postgresql/data

